# Alacritty Configuration

[general]
import = [
  "themes/mocha.toml",
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 110, lines = 34 }
padding = { x = 3, y = 0 }
opacity = 0.95
blur = true
resize_increments = true

[cursor]
style = "Block"

[bell]
duration = 0

[scrolling]
history = 5000
multiplier = 3

[selection]
save_to_clipboard = true

[font]
size = 11

[font.normal]
family = "SF Mono SC"
style = "Regular"

[terminal]
shell = { program = "C:/Git/bin/bash", args = ["--login", "-i"] }

[mouse]
bindings = [
  { mouse = "Right", action = "PasteSelection"},
]

[keyboard]
bindings = [
  { key = "Space",  mods = "Control",       chars = "\u0000" },
  { key = "Slash",  mods = "Control",       chars = "\u001f" },
  { key = "Key1",   mods = "Alt",           chars = "\u001b1" },
  { key = "Key2",   mods = "Alt",           chars = "\u001b2" },
  { key = "Key3",   mods = "Alt",           chars = "\u001b3" },
  { key = "Key4",   mods = "Alt",           chars = "\u001b4" },
  { key = "Key5",   mods = "Alt",           chars = "\u001b5" },
  { key = "Key6",   mods = "Alt",           chars = "\u001b6" },
  { key = "Key7",   mods = "Alt",           chars = "\u001b7" },
  { key = "Key8",   mods = "Alt",           chars = "\u001b8" },
  { key = "Key9",   mods = "Alt",           chars = "\u001b9" },
  { key = "Minus",  mods = "Alt",           chars = "\u001b-" },
  { key = "L",      mods = "Control|Shift", chars = "printf \"\\033c\"\n" },
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "N",      mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Space",  mods = "Control|Shift", action = "ToggleViMode" },
  { key = "Q",      mods = "Control|Shift", action = "ToggleViMode" },
  { key = "Enter",  mode = "Vi|~Search",    action = "Copy" },
  { key = "Enter",  mode = "Vi|~Search",    action = "ClearSelection" },
  { key = "Enter",  mode = "Vi|~Search",    action = "ToggleViMode" },
]
